name: 'Build and upload to Browserstack'

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform' 
        required: true
        type: choice
        options:
        - ios
        - android
      flavor:
        description: 'Flavor'
        required: true
        type: choice
        options:
        - dev
        - acc
        - prod
      environment:
        type: environment

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Print inputs
      run: |
          echo "Platform: ${{inputs.platform}}"
