on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: ./.github/actions/install-flutter

      - name: Install dependencies
        run: |
          fvm flutter pub get

      - name: Run tests
        run: |
          fvm flutter test --coverage