on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.APP_READ_ACCESS_REPOSITORIES_PRIVATE_KEY }}

      - run: |
            echo "Adding SSH key to known hosts"
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
          
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.APP_READ_ACCESS_REPOSITORIES_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v4
        with:
          name: git@github:com:flutter-sandbox/flutter-demo-plugin:git
          ref: main

      - name: Install Flutter
        uses: ./.github/actions/install-flutter

      - name: Install dependencies
        run: |
          dart pub get

      - name: Run tests
        run: |
          flutter test --coverage
